import Foundation

/// Represents a "Smart Jump Point" generated by AI analysis
struct SmartChapter: Identifiable, Codable {
    let id: UUID
    let time: Double     // The timestamp in seconds
    let title: String    // e.g. "Intro", "Deep Dive"
    let summary: String  // The transcribed text preview
    
    init(time: Double, title: String, summary: String) {
        self.id = UUID()
        self.time = time
        self.title = title
        self.summary = summary
    }
}
